update
asg0451/scotty_auth_test pull request #2
Opened 2017-01-19 12:19 UTC by i-zhen

add logout ability

2017-01-19 23:17 UTC, asg0451 requested changes
Thanks for the PR. Some requests: please make a test case for this function, add haddock documentation (follow format in authCheck), and add this to the example haddock comment at the top of the file. other than that good shit! i never thought to add a logout route. what led you to come across my repo?

2017-01-19 23:17 UTC, asg0451 commented on src/Web/Scotty/Login/Session.hs
> +    Nothing -> status internalServerError500
this should 404, not 500.

2017-01-19 23:17 UTC, asg0451 commented on src/Web/Scotty/Login/Session.hs
> +      let session = find (\lambda -> sessionSid lambda == T.fromStrict v) vaultContents
change 'lambda' to something useful, like 'session' or 'sesh' or even 's'

2017-01-19 23:17 UTC, asg0451 commented on src/Web/Scotty/Login/Session.hs
> +        Nothing -> status internalServerError500
again, 404

2017-01-20 14:16 UTC, i-zhen commented
Sorry for the carelessly work. I just would like to implement the logout ability in my website. I may work for this later.

2017-01-20 14:16 UTC, closed without merging

2017-01-20 14:20 UTC, asg0451 commented
no worries, i welcome future contributions. i may implement this sometime over the weekend if i get bored, i just pushed a bunch of optimizations and changes anyway. let me know if you have any other feature requests. 

out of curiosity, are you using this package? I'm using it for my site but i thought i was the only one. it's definitely not production-ready yet but i think it works well enough.

2017-01-20 14:23 UTC, i-zhen commented
Yes, I'm using it with Scotty. I built a Hacker News-like website and it works for my site.